name: Build Watch App

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install pebble-tool
        run: uv tool install pebble-tool --python 3.11

      - name: Fix progressbar bug
        run: python3 patch_pebble.py

      - name: Install Pebble SDK
        run: |
          mkdir -p ~/.pebble-sdk
          touch ~/.pebble-sdk/NO_TRACKING
          pebble sdk install https://github.com/aveao/PebbleArchive/raw/master/SDKCores/sdk-core-4.3.tar.bz2

      - name: Build
        run: yes | pebble build

      - name: Upload PBW
        uses: actions/upload-artifact@v4
        with:
          name: AI-Assistant-for-Pebble
          path: build/app.pbw
          retention-days: 90
        
